name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: YuGiOh_PoC_Patcher
      Project_Path: YuGiOh_PoC_Patcher/YuGiOh_PoC_Patcher.csproj    # Replace with your project path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}.sln

    - name: Build
      run: |
        msbuild ${{ env.Solution_Name }}.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=x64

    - name: Publish artifacts
      if: matrix.configuration == 'Release' && success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.Solution_Name }}-${{ matrix.configuration }}
        path: |
          ${{ env.Project_Path }}/bin/${{ matrix.configuration }}/net8.0-windows
          !**/*.pdb
          !**/*.obj
