name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: YuGiOh_PoC_Patcher

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Setup Visual Studio environment (includes .NET Framework)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet Packages
      run: nuget restore ${{ env.Solution_Name }}.sln

    # Build the solution
    - name: Build Solution
      run: |
        msbuild ${{ env.Solution_Name }}.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /p:UseSharedCompilation=false

    # Publish artifacts
    - name: Publish artifacts
      if: matrix.configuration == 'Release' && success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.Solution_Name }}-${{ matrix.configuration }}
        path: |
          YuGiOh_PoC_Patcher/bin/${{ matrix.configuration }}
          CustomControls/*/bin/${{ matrix.configuration }}
          !**/*.pdb
          !**/*.obj
